# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

#### START BLOCK ####
# This block is responsible for properly configuring project with required dependencies
# Copy-paste it whenever you need to update to newer TerrariaCraft!

# Base64 blob of TerrariaCraft alongside all of its required sub-libraries.
tc_build_data=b3JnLnplaXRoLkhhbW1lckxpYjpIYW1tZXJMaWItMS4xMi4yOjEyLjIuNTE6ZGVvYmYhDQp8b3JnLnplaXRoLmhhbW1lcmFuaW1zOkhhbW1lckFuaW1hdGlvbnMtMS4xMi4yOjEyLjIuMzU6ZGVvYmYhDQp8b3JnLnplaXRoLk11c2ljTGF5ZXI6TXVzaWNMYXllci0xLjEyLjI6MTIuMi4yMg0KfG9yZy56ZWl0aC5DdWJpY0NodW5rczpDdWJpY0NodW5rcy0xLjEyLjI6MC4wLjEyMDguMCE+DQp8b3JnLnplaXRoLk1jQ3VlOk1jQ3VlLTEuMTIuMjoxMi40LjEwDQp8b3JnLnplaXRoLnZpdmVhcGk6Vml2ZWNyYWZ0QVBJLTEuMTIuMjoxMi4xLjENCnxvcmcuemVpdGguQ29sb3JlZEx1eDpDb2xvcmVkTHV4LTEuMTIuMjoxMi42LjMzDQoNCnxvcmcuemVpdGgudGVycmFyaWE6VGVycmFyaWFDcmFmdFJlY2lwZVZpZXdlci0xLjEyLjI6Ni4wLjINCg0KfGlvLmdpdGh1Yi5sbGFtYWxhZDc6bWl4aW5leHRyYXMtY29tbW9uOjAuMy41

# In-game information
mc_username=Dev
mc_uuid=00000000000000000000000000000000

# For OpenAL to work
natives_dir=

##### END BLOCK #####